# Generated by Django 5.1.3 on 2024-11-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('upload_notes', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=100)),
            ],
        ),
    ]
