# Generated by Django 5.1.3 on 2024-11-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteSwap_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesID', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
            ],
        ),
    ]
