# Generated by Django 5.1.3 on 2024-11-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteSwap_main', '0002_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='users',
        ),
    ]
