# Generated by Django 5.0.7 on 2024-11-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteSwap_main', '0004_rename_upload_notes_users_uploaded_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='university',
        ),
        migrations.RemoveField(
            model_name='users',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='users',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='users',
            name='university',
        ),
        migrations.RemoveField(
            model_name='users',
            name='uploaded_notes',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_role',
        ),
    ]
