# Generated by Django 5.0.7 on 2024-11-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteSwap_main', '0005_remove_notes_dept_remove_notes_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='uploaded_notes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notesID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
