# Generated by Django 5.1.3 on 2024-11-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteSwap_main', '0006_notes_rating_notes_subject_notes_university_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
